#!/usr/bin/env node
/* Regenerates js/export/cssStrings.js from css/sheet.css, css/themes.css and css/print.css.
 * The standalone HTML export must inline the CSS, and file:// pages cannot fetch() it.
 * Usage: node tools/sync-css.js [--check]   (--check exits 1 when cssStrings.js is out of date)
 */
'use strict';
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const SOURCES = [
  ['SHEET_CSS', 'css/sheet.css'],
  ['THEMES_CSS', 'css/themes.css'],
  ['PRINT_CSS', 'css/print.css']
];
const target = path.join(root, 'js', 'export', 'cssStrings.js');

function read(rel) {
  return fs.readFileSync(path.join(root, rel), 'utf8').replace(/\r\n?/g, '\n');
}

function generate() {
  const lines = [
    '/* Songsheets — the CSS files as strings, for the standalone HTML export.',
    ' * GENERATED by tools/sync-css.js from ' + SOURCES.map((s) => s[1]).join(', ') + '; do not edit.',
    ' * Browser: window.SongSheets.export.cssStrings   Node: require(\'./cssStrings.js\')',
    ' */',
    '(function (root) {',
    '  \'use strict\';',
    '  var isNode = typeof module !== \'undefined\' && module.exports;',
    '  var api = {'
  ];
  SOURCES.forEach(([name, rel], i) => {
    lines.push('    ' + name + ': ' + JSON.stringify(read(rel)) + (i < SOURCES.length - 1 ? ',' : ''));
  });
  lines.push(
    '  };',
    '  root.SongSheets = root.SongSheets || {};',
    '  root.SongSheets.export = root.SongSheets.export || {};',
    '  root.SongSheets.export.cssStrings = api;',
    '  if (isNode) module.exports = api;',
    '})(typeof globalThis !== \'undefined\' ? globalThis : this);',
    ''
  );
  return lines.join('\n');
}

const out = generate();
if (process.argv.includes('--check')) {
  const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8').replace(/\r\n?/g, '\n') : '';
  if (current !== out) {
    console.error('js/export/cssStrings.js is out of date; run: node tools/sync-css.js');
    process.exit(1);
  }
  console.log('js/export/cssStrings.js is up to date');
} else {
  fs.writeFileSync(target, out);
  console.log('wrote ' + path.relative(root, target));
}
